[110.target.Train] # NEXUSTRAINMOTHERSHIP_MOTHERSHIP
produces = 10 # MOTHERSHIP

[1632.target.Build] # TRAINQUEEN_QUEEN
produces = 126 # QUEEN

[2704.target.Build] # EFFECT_SPAWNLOCUSTS
produces = 693 # LOCUSTMPFLYING

[421.target.BuildInstant] # BUILD_TECHLAB_BARRACKS
produces = 37 # BARRACKSTECHLAB

[422.target.BuildInstant] # BUILD_REACTOR_BARRACKS
produces = 38 # BARRACKSREACTOR

[454.target.BuildInstant] # BUILD_TECHLAB_FACTORY
produces = 39 # FACTORYTECHLAB

[455.target.BuildInstant] # BUILD_REACTOR_FACTORY
produces = 40 # FACTORYREACTOR

[487.target.BuildInstant] # BUILD_TECHLAB_STARPORT
produces = 41 # STARPORTTECHLAB

[488.target.BuildInstant] # BUILD_REACTOR_STARPORT
produces = 42 # STARPORTREACTOR

[4119.target.Morph] # MORPHTOBANELING_BANELING
produces = 9 # BANELING

